FROM nginx:latest

RUN apt update
RUN apt upgrade -y
RUN apt install curl -y
RUN apt-get install sudo
RUN curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -
RUN sudo apt install nodejs
RUN sudo apt install build-essential -y
ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN mkdir air-front-end

COPY air-front-end/ /air-front-end
WORKDIR /air-front-end
RUN npm install
RUN npm run build
RUN mv build/* /usr/share/nginx/html

EXPOSE 80

STOPSIGNAL SIGTERM

CMD ["nginx","-g","daemon off;"]
