version: '3.8'
services:
  webserver:
    build: .
    image: nginx:latest
    ports:
      - 8080:80
    container_name: air_frontend
    restart: always   
  mysql:
    image: mysql:latest
    ports:
      - 3366:3306
    container_name: air_database
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/my_secret
    secrets: 
      - my_secret
secrets:
  my_secret:
    file: ./my_secret.txt