# Generated by Django 4.1 on 2022-12-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True, verbose_name="date")),
                ("pc4", models.IntegerField(max_length=35, verbose_name="PC4")),
                ("pm10", models.FloatField(max_length=35, verbose_name="pm10")),
                ("pm2_5", models.FloatField(max_length=35, verbose_name="pm2.5")),
                ("no2", models.FloatField(max_length=35, verbose_name="no2")),
                ("no", models.FloatField(max_length=35, verbose_name="no")),
                ("so2", models.FloatField(max_length=35, verbose_name="so2")),
            ],
        ),
    ]
