# Generated by Django 4.1 on 2022-12-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airquality",
            name="pc4",
            field=models.IntegerField(verbose_name="PC4"),
        ),
    ]
