# Generated by Django 4.1 on 2022-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_api", "0002_alter_airquality_pc4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airquality",
            name="pc4",
            field=models.CharField(max_length=35, verbose_name="pc4"),
        ),
        migrations.AlterField(
            model_name="airquality",
            name="pm2_5",
            field=models.FloatField(max_length=35, verbose_name="pm2_5"),
        ),
    ]
