import React from 'react';
import "./area.page.css";
import {useLocation} from 'react-router-dom';

export default function AreaPage() {
    let  location = useLocation();
    return (
        <div className={'area-layout'}>
            <div className={'area-top-content'}>
                <div className={'top-content-controls custom-container'}>
                    <div className={'zipcode'}>Zip Code</div>
                    <h1>{location.state.pc4_code}</h1>
                </div>
                <div className={'top-content-extra-controls'}>
                    <div className={'custom-btn'}>
                        Placeholder1
                    </div>
                    <div className={'custom-btn'}>
                        Placeholder2
                    </div>
                    <div className={'custom-btn'}>
                        Placeholder3
                    </div>
                </div>
            </div>
            <div className={'custom-container area-info-content'}>
                <div className={'area-info-top'}>
                    <img src="" alt="area image"/>
                    <h2>Title</h2>
                </div>
                <p className={'area-info-bottom'}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitasse platea dictumst quisque sagittis purus sit. Dignissim sodales ut eu sem integer vitae justo. Interdum velit laoreet id donec ultrices. Sociis natoque penatibus et magnis dis. Massa tempor nec feugiat nisl pretium fusce id. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Sagittis vitae et leo duis ut diam. Nulla malesuada pellentesque elit eget gravida. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Vulputate dignissim suspendisse in est.

                    Arcu bibendum at varius vel. Nascetur ridiculus mus mauris vitae ultricies leo. Fringilla urna porttitor rhoncus dolor. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. Eget sit amet tellus cras. Purus sit amet luctus venenatis. Porttitor massa id neque aliquam. Adipiscing diam donec adipiscing tristique risus nec feugiat in fermentum. Magna sit amet purus gravida quis blandit turpis cursus. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget egestas purus viverra accumsan. Ultrices tincidunt arcu non sodales neque sodales ut. Cras sed felis eget velit. Sit amet consectetur adipiscing elit ut aliquam purus. Mauris rhoncus aenean vel elit scelerisque mauris. Purus sit amet volutpat consequat mauris nunc congue nisi.

                    Viverra ipsum nunc aliquet bibendum enim facilisis gravida. Egestas maecenas pharetra convallis posuere morbi leo urna molestie. Leo urna molestie at elementum eu facilisis sed odio. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Vulputate odio ut enim blandit volutpat maecenas. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Gravida quis blandit turpis cursus in. Tellus elementum sagittis vitae et leo duis ut diam quam. Non quam lacus suspendisse faucibus. At elementum eu facilisis sed odio morbi quis commodo. Odio facilisis mauris sit amet massa vitae tortor condimentum lacinia.

                    Cras ornare arcu dui vivamus arcu felis bibendum. Nunc eget lorem dolor sed viverra ipsum nunc. Dui vivamus arcu felis bibendum. Mi bibendum neque egestas congue quisque egestas. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Ullamcorper morbi tincidunt ornare massa. Nunc non blandit massa enim nec dui nunc mattis. Augue lacus viverra vitae congue eu consequat. Ac placerat vestibulum lectus mauris ultrices eros. Malesuada bibendum arcu vitae elementum curabitur. Faucibus in ornare quam viverra. Felis eget velit aliquet sagittis id consectetur. Diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Malesuada fames ac turpis egestas integer eget aliquet. Fermentum iaculis eu non diam phasellus vestibulum. Ut sem nulla pharetra diam sit amet.

                    Suspendisse potenti nullam ac tortor vitae purus faucibus. Mauris pharetra et ultrices neque ornare aenean euismod. Volutpat consequat mauris nunc congue nisi vitae. Nascetur ridiculus mus mauris vitae. Facilisis sed odio morbi quis commodo odio aenean sed adipiscing. Enim nec dui nunc mattis enim ut tellus. Condimentum lacinia quis vel eros donec ac odio. Quis viverra nibh cras pulvinar mattis. Commodo ullamcorper a lacus vestibulum sed arcu non. Dignissim enim sit amet venenatis urna cursus eget. Amet purus gravida quis blandit turpis cursus in hac habitasse. Rhoncus dolor purus non enim praesent elementum facilisis. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Euismod quis viverra nibh cras pulvinar mattis nunc. Tellus mauris a diam maecenas sed enim ut sem. Diam phasellus vestibulum lorem sed risus ultricies.

                    Sit amet consectetur adipiscing elit duis tristique. Eu feugiat pretium nibh ipsum consequat nisl. Massa placerat duis ultricies lacus. Hendrerit gravida rutrum quisque non. Sit amet volutpat consequat mauris nunc congue nisi. Pellentesque massa placerat duis ultricies lacus sed turpis. Nec ultrices dui sapien eget mi proin sed libero. Orci porta non pulvinar neque laoreet suspendisse. In est ante in nibh mauris cursus. Tincidunt eget nullam non nisi est sit amet facilisis. Sollicitudin ac orci phasellus egestas tellus rutrum tellus.

                    Integer malesuada nunc vel risus commodo viverra maecenas accumsan. Nibh praesent tristique magna sit amet purus gravida quis. Vestibulum morbi blandit cursus risus at. Tellus cras adipiscing enim eu. Posuere urna nec tincidunt praesent semper. Commodo quis imperdiet massa tincidunt nunc pulvinar. Lacus laoreet non curabitur gravida arcu ac. Cras semper auctor neque vitae tempus quam pellentesque nec. Feugiat in fermentum posuere urna nec. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Bibendum est ultricies integer quis auctor elit sed. Tortor consequat id porta nibh. Velit ut tortor pretium viverra. Auctor augue mauris augue neque gravida in.

                    Bibendum ut tristique et egestas quis. Habitant morbi tristique senectus et netus et malesuada fames. Velit dignissim sodales ut eu sem. Egestas egestas fringilla phasellus faucibus. Eu mi bibendum neque egestas congue quisque egestas diam. Cras sed felis eget velit aliquet sagittis id consectetur purus. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida neque. Facilisis mauris sit amet massa vitae tortor. Dictum non consectetur a erat. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Ullamcorper malesuada proin libero nunc. Urna et pharetra pharetra massa massa ultricies mi. Blandit turpis cursus in hac. Ut tellus elementum sagittis vitae et.

                    Arcu vitae elementum curabitur vitae nunc. Erat velit scelerisque in dictum non. Elementum nisi quis eleifend quam. Ac turpis egestas maecenas pharetra convallis posuere morbi. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Morbi blandit cursus risus at ultrices. Facilisis leo vel fringilla est ullamcorper. Augue eget arcu dictum varius duis at consectetur lorem donec. Non arcu risus quis varius quam quisque id. Varius duis at consectetur lorem donec massa sapien. Tempus urna et pharetra pharetra massa massa. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Ultrices gravida dictum fusce ut placerat orci. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Non tellus orci ac auctor augue mauris. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Nisi porta lorem mollis aliquam ut.

                    Egestas sed sed risus pretium. Euismod quis viverra nibh cras pulvinar mattis. In aliquam sem fringilla ut. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. In fermentum et sollicitudin ac. Eu turpis egestas pretium aenean pharetra. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Sed libero enim sed faucibus turpis. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Pretium vulputate sapien nec sagittis aliquam malesuada. Volutpat diam ut venenatis tellus in metus vulputate. At lectus urna duis convallis. At ultrices mi tempus imperdiet nulla malesuada. Amet massa vitae tortor condimentum lacinia. In aliquam sem fringilla ut morbi tincidunt augue interdum. Sit amet luctus venenatis lectus magna. Sem et tortor consequat id.

                    At in tellus integer feugiat scelerisque varius morbi enim. Ultrices tincidunt arcu non sodales. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Risus pretium quam vulputate dignissim suspendisse in est ante. Sed adipiscing diam donec adipiscing. Nulla facilisi nullam vehicula ipsum. Vitae suscipit tellus mauris a diam maecenas sed. Morbi tristique senectus et netus. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Lorem ipsum dolor sit amet consectetur adipiscing.

                    Amet nulla facilisi morbi tempus iaculis urna id volutpat. Bibendum at varius vel pharetra vel. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Est sit amet facilisis magna etiam tempor orci eu. Morbi leo urna molestie at elementum eu facilisis. Placerat duis ultricies lacus sed turpis. Quam viverra orci sagittis eu volutpat odio facilisis mauris sit. Non diam phasellus vestibulum lorem sed. Orci eu lobortis elementum nibh tellus. Varius morbi enim nunc faucibus a pellentesque sit amet porttitor. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Ac tincidunt vitae semper quis. Sed vulputate mi sit amet mauris commodo quis imperdiet. Egestas sed sed risus pretium quam vulputate. Tincidunt eget nullam non nisi.

                    Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Vitae elementum curabitur vitae nunc sed velit. Sit amet consectetur adipiscing elit pellentesque habitant morbi. Lectus urna duis convallis convallis tellus id. Dictum fusce ut placerat orci nulla pellentesque dignissim enim sit. Risus pretium quam vulputate dignissim. Risus ultricies tristique nulla aliquet. Vestibulum rhoncus est pellentesque elit. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Pellentesque id nibh tortor id aliquet lectus proin nibh. Eget nulla facilisi etiam dignissim. Nibh ipsum consequat nisl vel pretium. Varius duis at consectetur lorem donec. Tristique senectus et netus et malesuada fames ac. Eu sem integer vitae justo eget magna fermentum iaculis eu. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. Donec ac odio tempor orci. In fermentum posuere urna nec.

                    Elementum pulvinar etiam non quam. Leo a diam sollicitudin tempor id eu nisl nunc mi. Consequat ac felis donec et odio pellentesque diam. Tortor consequat id porta nibh venenatis cras sed felis eget. Sollicitudin ac orci phasellus egestas tellus rutrum tellus. Ullamcorper malesuada proin libero nunc consequat interdum varius sit. Pellentesque nec nam aliquam sem et. A arcu cursus vitae congue mauris. Vel quam elementum pulvinar etiam. Id leo in vitae turpis massa sed elementum tempus egestas. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero id. Nisi lacus sed viverra tellus in hac habitasse platea. Et tortor consequat id porta nibh venenatis cras sed felis. Ac feugiat sed lectus vestibulum mattis ullamcorper velit. Id aliquet lectus proin nibh nisl condimentum id venenatis a.

                    Sit amet venenatis urna cursus eget. Nec feugiat nisl pretium fusce. Amet porttitor eget dolor morbi non arcu risus quis varius. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Diam quam nulla porttitor massa id neque aliquam vestibulum morbi. Pharetra vel turpis nunc eget lorem. Nibh praesent tristique magna sit amet. Maecenas ultricies mi eget mauris pharetra et ultrices neque. Vitae justo eget magna fermentum iaculis eu non diam. Justo laoreet sit amet cursus sit amet dictum. Varius duis at consectetur lorem. Tempus imperdiet nulla malesuada pellentesque. Id ornare arcu odio ut sem. Turpis nunc eget lorem dolor sed viverra ipsum nunc aliquet. Faucibus pulvinar elementum integer enim neque volutpat. Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Lectus sit amet est placerat in egestas erat. Id velit ut tortor pretium viverra suspendisse potenti nullam.

                    Facilisi cras fermentum odio eu. Nulla facilisi nullam vehicula ipsum a arcu. Euismod quis viverra nibh cras. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Tincidunt id aliquet risus feugiat in ante metus dictum. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Feugiat nibh sed pulvinar proin gravida hendrerit. Enim sed faucibus turpis in. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus.

                    At lectus urna duis convallis. Integer feugiat scelerisque varius morbi enim. Condimentum mattis pellentesque id nibh. Arcu ac tortor dignissim convallis aenean et tortor at. Sit amet tellus cras adipiscing enim eu turpis. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Eu scelerisque felis imperdiet proin fermentum. Nisl nunc mi ipsum faucibus vitae aliquet nec. Diam maecenas sed enim ut sem viverra aliquet eget. Id faucibus nisl tincidunt eget nullam non. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Feugiat pretium nibh ipsum consequat. Magna sit amet purus gravida quis blandit turpis cursus in.

                    Vitae tortor condimentum lacinia quis vel eros donec ac. Egestas fringilla phasellus faucibus scelerisque eleifend. Posuere morbi leo urna molestie at. Cras ornare arcu dui vivamus arcu felis. Eget arcu dictum varius duis at consectetur. At volutpat diam ut venenatis. Amet nisl purus in mollis nunc sed id. Ornare arcu dui vivamus arcu felis. Magna fringilla urna porttitor rhoncus. Vitae nunc sed velit dignissim sodales ut eu sem. Elementum tempus egestas sed sed risus pretium quam vulputate dignissim. Vestibulum sed arcu non odio euismod lacinia at. Risus at ultrices mi tempus imperdiet nulla. Aliquam nulla facilisi cras fermentum odio eu. Proin sed libero enim sed faucibus turpis in eu mi. Proin nibh nisl condimentum id venenatis a condimentum. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Urna et pharetra pharetra massa massa ultricies mi.

                    Dolor sit amet consectetur adipiscing elit. Massa vitae tortor condimentum lacinia quis vel. Nibh tortor id aliquet lectus proin nibh. Eu non diam phasellus vestibulum lorem sed risus ultricies. Enim blandit volutpat maecenas volutpat blandit. Mi eget mauris pharetra et. Diam maecenas ultricies mi eget mauris. Volutpat lacus laoreet non curabitur gravida arcu ac tortor. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Urna id volutpat lacus laoreet non. Neque sodales ut etiam sit amet. Non quam lacus suspendisse faucibus interdum posuere lorem. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Ut pharetra sit amet aliquam id diam maecenas ultricies.

                    Vitae auctor eu augue ut lectus arcu. Cursus mattis molestie a iaculis at erat pellentesque. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Auctor augue mauris augue neque gravida in fermentum et sollicitudin. Congue nisi vitae suscipit tellus. Tempus quam pellentesque nec nam aliquam. Convallis aenean et tortor at. Amet consectetur adipiscing elit pellentesque habitant. Quis lectus nulla at volutpat diam ut venenatis tellus. Odio pellentesque diam volutpat commodo sed egestas egestas. Nisi porta lorem mollis aliquam. Nunc faucibus a pellentesque sit. Congue quisque egestas diam in arcu cursus. Sodales ut eu sem integer vitae justo eget magna fermentum. Scelerisque mauris pellentesque pulvinar pellentesque habitant. In tellus integer feugiat scelerisque. Sollicitudin ac orci phasellus egestas tellus. Purus sit amet luctus venenatis lectus magna fringilla.
                </p>
            </div>
            <div className={'area-chart-content'}>
                <div className={'custom-container chart-area'}>

                </div>
                <div className={'custom-container chart-area'} style={{marginTop: "auto"}}>

                </div>
            </div>
        </div>
    );
}
